# Generated by Django 4.0.1 on 2022-01-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socialsecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('ssnumber', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
